### ISSUE TITLE
Repository cannot be deleted because a run is linked to it

### ISSUE THREAD

**Issue by MarcelBochtler** [eclipse-apoapsis/ort-server#100]
Whenever an ORT run was started for a repository, one can no longer delete this repository:

```
DELETE https://.../api/v1/repositories/123

Request uses authentication

HTTP/1.1 500 Internal Server Error
x-engine: Ktor
date: Tue, 16 Apr 2024 15:02:08 GMT
server: Ktor/2.3.8
content-length: 301
content-type: application/json

{
  "message": "Error when processing the request.",
  "cause": "org.postgresql.util.PSQLException: ERROR: update or delete on table \"repositories\" violates foreign key constraint \"ort_runs_repository_id_fkey\" on table \"ort_runs\"\n  Detail: Key (id)=(123) is still referenced from table \"ort_runs\"."
}
```

**Comment by sschuberth** [comment]
As a related question, what should happen to a run if a repository gets deleted meanwhile? Should the run be cancelled? Should the deletion be postponed until the run completes? Should the user be able to choose?

**Comment by Etsija** [comment]
I'd like to add to this that there also seems to be no endpoint for deleting ORT runs, and I think there should be; we are at the moment trying to fix the broken docker compose local development environment, to advance the ORT Server UI project, and in the process I'm creating lots of new ORT runs for a repo, then reading the next server crash from the logs, then debugging further.

The result of this is a lot of broken ORT runs for the repo, and no way to delete the runs - and so, no way to delete the repo from the local DB, either.

**Comment by wkl3nk** [comment]
With the 2nd of 2 commits, now the endpoints for deleting ORT runs are fully functional. See https://github.com/eclipse-apoapsis/ort-server/commit/2696a26831546cc02f413beab0de59f49164e8f1 (new endpoints and deletion in database) and https://github.com/eclipse-apoapsis/ort-server/commit/c25ebd767dfd512c10eda71d8a05a1d01f47373d (deletion of generated reports in storage)
