### ISSUE TITLE
React does not recognize the X prop on a DOM element

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#1028]
In [this commit](https://github.com/eclipse-apoapsis/ort-server/commit/bf74b0b65722321ec37a0b9e40e4038c86ed90a3), `DataTablePagination` was changed to use props instead of table context, to provide type safety for links. This creates a lot of React warnings in dev console for every page:

_Warning: React does not recognize the `X` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `X` instead. If you accidentally passed it from a parent component, remove it from the DOM element._
```
a
Link<@http://localhost:5173/node_modules/.vite/deps/chunk-535XYBFZ.js?v=1d5fd888:3583:35
div
div
DataTablePagination@http://localhost:5173/src/components/data-table/data-table-pagination.tsx:34:36
div
div
DataTable@http://localhost:5173/src/components/data-table/data-table.tsx:31:26
div
```

@mmurto any idea to fix this?  [This seems to be related](https://stackoverflow.com/questions/54468535/how-to-solve-warning-react-does-not-recognize-the-x-prop-on-a-dom-element), and the props in the warnings list router provider's props as well as the `setPageSizeOptions` and `setCurrentPageOptions` of the `DataTablePagination` component. Seems as if the router provider's props are "leaking" down to the pagination component.

**Comment by mmurto** [comment]
Likely caused by [this](https://github.com/eclipse-apoapsis/ort-server/commit/bf74b0b65722321ec37a0b9e40e4038c86ed90a3#diff-cf45d3d4a89cda79fdb75e867af489175bb99714447a2f78bf20e68af69f1109R228-R239), as the destructured `Route` is returned to the links, and that includes additional properties that link doesn't want. Can be seen in the rendered html:

```html
<a options="[object Object]" originalindex="3" parentroute="[object Object]" _path="/" _id="/_layout/" _fullpath="/" _to="/" rank="45" _lazypromise="[object Promise]" role="link" aria-disabled="true">
```

So the solution is to not destructure `Route` for the function but only take the needed items, probably just `to`, `search` and `params`.

**Comment by Etsija** [comment]
I can investigate if you're busy.

**Comment by Etsija** [comment]
@mmurto got rid of all other warnings, but these remain:

Warning: React does not recognize the `setPageSizeOptions` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setpagesizeoptions` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
div
DataTable@http://localhost:5173/src/components/data-table/data-table.tsx:31:26
div
_c9@http://localhost:5173/src/components/ui/card.tsx:103:9
div

and the same for `setCurrentPageOptions`. I am at loss as to how to fix that, and I'd like to get rid of these if I can, to clear the dev console for more important stuff.

**Comment by mmurto** [comment]
Can you push the current code and I'll check?

**Comment by mmurto** [comment]
I'd guess it's [this](https://github.com/eclipse-apoapsis/ort-server/blob/73e637f1cd74acaf91447626d0218a3485fbef3d/ui/src/components/data-table/data-table.tsx#L58-L61). You'll need to first extract the violating props (setPageSizeOptions, setCurrentPageOptions) from the props and then pass the remaining props to the div, like in the SO answer you linked.
