### ISSUE TITLE
Document what a repo for config provider `github-config` should include

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#104]
We're trying to run ORT Server with [ORT's config repo](https://github.com/oss-review-toolkit/ort-config) to be provided by `github-config`. We get the following error:

```
ort-server-config-worker-1     | 2024-04-18 06:20:49.694 [pool-1-thread-4] level=DEBUG o.e.a.o.c.g.GitHubConfigFileProvider - GET 'https://api.github.com/repos/oss-review-toolkit/ort-config/contents/ort-server.params.kts?ref=e5cf91ddd8b994587a7a82815f094ce9fdb27379'
ort-server-config-worker-1     | 2024-04-18 06:20:49.909 [pool-1-thread-4] level=ERROR o.e.a.o.w.config.ConfigComponent - Config worker job failed for run '10'.
ort-server-config-worker-1     | org.eclipse.apoapsis.ortserver.config.ConfigException: The requested path doesn't exist in the specified branch.
```

What is `ort-server.params.kts` and what else should the config repo provided by `github-config` include?

**Comment by sschuberth** [comment]
I wonder whether we could simply not require the file to be present here

https://github.com/eclipse-apoapsis/ort-server/blob/3ff9fcce6f49aab741098f67ffdaab7a2558ad7a/workers/config/src/main/kotlin/ConfigWorker.kt#L83-L84

in which case no validation would be performed at all.

**Comment by sschuberth** [comment]
@mmurto, @etsija, can you check whether https://github.com/eclipse-apoapsis/ort-server/pull/105 would work for us?

**Comment by sschuberth** [comment]
> Running the config worker if there is no parameter validation script is a waste of resources

But wouldn't the config worker still need to run to check whether a config script has been added in between? It could be inconvenient to force the user to also enable a config option in that case. On the other hand, if you'd want to temporarily disable an existing config validation, such an option could make sense.

**Comment by Etsija** [comment]
As a workaround, I did this:
- forked the oss-review-toolkit/ort-config repo to doubleopen-project/ort-server-config
- in that repo, put the validation-success.params.kts file, renamed to ort-server.params.kts
- I believe this then acts as a "dummy pass" file, always returning a success for the validation

This was an ugly hack, and probably needs to be handled more smoothly. But it did result in a successful ORT run (finally, with some docker-compose and load-configuration changes as well).

**Comment by oheger-bosch** [comment]
@mnonnenmacher: The config worker cannot be fully skipped. It also updates the database to store the resolved configuration context and the resolved configuration. This information is later accessed by the other workers.

@sschuberth: Since the configuration validation is a rather central and important mechanism, I would prefer that this is explicitly configured. There is a TODO comment in the code to make the path to the validation script configurable. If this was implemented, a missing path configuration could be interpreted that no validation script needs to be executed.
