### ISSUE TITLE
Access token becomes too long when too many roles added to a user

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#1058]
When testing the Groups endpoints, by setting several (5) groups rights to one user, I noticed organizations endpoint returns a 400 Bad Request. Investigating further, I noticed the authorization header cannot be sent anymore.

1. Adding only one groups right to a user: auth header is sent, connection OK, UI works OK.

![Capture2](https://github.com/user-attachments/assets/cc0b07f7-94ae-4393-9e84-2c56cd877778)
![Capture1](https://github.com/user-attachments/assets/ecef037f-b553-44ee-9e95-7b47e6124635)

2. Adding five different groups rights to a user: auth header is _empty_, 400 Bad Request.

![Capture6](https://github.com/user-attachments/assets/4dae59db-5f9b-450b-908d-7e2dfcf49af6)
![Capture3](https://github.com/user-attachments/assets/bbcb62e2-7d4c-45ea-953e-4af1b3e6e245)
![Capture4](https://github.com/user-attachments/assets/810194f0-9793-4d0e-81cc-09529a178aca)
![Capture5](https://github.com/user-attachments/assets/cc3c0f5d-2232-4df1-823c-a4c6f7737820)

@mnonnenmacher Johanna recalls that you were saying you've found (and possibly fixed) this problem internally, so could you please advise? My hunch is, if the groups roles are part of the auth token, it becomes too long and fails to be included in the requests.

We have currently no other means to overcome this problem but 
- delete all but one user's groups rights from Keycloak
- delete cookies and session storage from browser
- then the user can log in again

As to the limit of groups the user can currently be attached to, I don't have the exact answer; I only know one group is OK, and five is not.

**Comment by Etsija** [comment]
To clarify: the question is _not_ how many groups you grant access to; it is rather how many roles are attached to those groups. I'm using a seeded repository in Docker Compose environment, which has a lot of products randomly seeded for each organization, and many repositories under those products.

Example: by just giving READERS access rights to three organizations, Keycloak has 270 separate roles attached to those three groups. This is probably the reason why so low number of groups access rights makes the access token too long.

**Comment by mnonnenmacher** [comment]
@Etsija Let me have a look at the Keycloak config in Compose. In general, we should refactor the way Keycloak is used (see #984) but that is not going to happen soon.

**Comment by mnonnenmacher** [comment]
@Etsija Could you try with the changes from #1064? With this the roles from the ort-server client are not mapped to the access token anymore.

**Comment by Etsija** [comment]
See my findings in #1064; the PR seems to resolve this issue.
