### ISSUE TITLE
RuleViolationService not configured in Module.kt

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#1169]
As the title says, `RuleViolationService` configuration is missing from [Module.kt](https://github.com/eclipse-apoapsis/ort-server/blob/main/core/src/main/kotlin/di/Module.kt). As a result, when the UI tries to use a generated query hook which uses the service, the back-end responds with an error:

![Screenshot from 2024-10-07 07-54-07](https://github.com/user-attachments/assets/ce4f166f-e223-4e56-a504-b7f3289958fa)

In addition to that, the endpoint also seems to be [missing an integration test](https://github.com/eclipse-apoapsis/ort-server/tree/main/core/src/test/kotlin/api). Probably that's why the non-functionality of the endpoint was not found during the PR.

**Comment by sschuberth** [comment]
@Etsija please try whether https://github.com/eclipse-apoapsis/ort-server/pull/1170 already solves the issue.

**Comment by Etsija** [comment]
It fixes this issue. However, I also noticed that sorting hasn't been implemented at all, and when no sorting parameter is given, the endpoint errors out. I'll create a separate issue for that.

**Comment by Etsija** [comment]
Please see also #1171.
