### ISSUE TITLE
ORT runs cannot be deleted

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#123]
Related to [this PR](https://github.com/eclipse-apoapsis/ort-server/issues/100), there really should be an endpoint to delete ORT runs from the database.  Currently, not being able to delete runs leads to cascading delete failure:

We have a hierarchy Organization -> Product -> Repository -> Run. Because runs cannot be deleted, none of the items going up in hierarchy can, either.

**Comment by mnonnenmacher** [comment]
@Etsija We are planning to work on that but first have to finish some other topics. I can't give you a date but this will definitely be implemented.

**Comment by Etsija** [comment]
Any estimates yet when this could be implemented?

**Comment by mnonnenmacher** [comment]
@Etsija Sorry, I can't give you an estimate. The item is high priority for us but we have to work on some other topics first, so better not expect it to be done within the next few weeks.

**Comment by sschuberth** [comment]
> Sorry, I can't give you an estimate.

Is there an update that allows you to commit to a time-line by now @mnonnenmacher?

**Comment by sschuberth** [comment]
The REST API endpoint was implemented by https://github.com/eclipse-apoapsis/ort-server/pull/1494. I've created https://github.com/eclipse-apoapsis/ort-server/issues/1505 as a follow-up.

**Comment by wkl3nk** [comment]
With the 2nd of 2 commits, now the endpoints for deleting ORT runs are fully functional. See https://github.com/eclipse-apoapsis/ort-server/commit/2696a26831546cc02f413beab0de59f49164e8f1 (new endpoints and deletion in database) and https://github.com/eclipse-apoapsis/ort-server/commit/c25ebd767dfd512c10eda71d8a05a1d01f47373d (deletion of generated reports in storage)
