### ISSUE TITLE
UI: Need a GitHub Action to build the UI

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#126]
This issue is targeted specifically for the Double Open team: 

As an automatic means to test that Renovate Bot's dependency updates for the UI work (as in "if it builds, it works"), a GitHub Action to build the UI should be added to the workflows that are run for PRs.

**Comment by sschuberth** [comment]
> as in "if it builds, it works"

@mnonnenmacher, this means we're now fine with merging UI dependency updates without further acknowledgement from our side. This should simply the process a bit.
