### ISSUE TITLE
Scanner gets stuck on creating file lists

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#1295]
Commit https://github.com/eclipse-apoapsis/ort-server/commit/851212d2458e28343b0b34e27b7d0182b0be9bc4 seems to have introduced a bug in Scanner Worker. The bug can be reproduced by creating run for https://github.com/jshttp/mime-types on revision 4b3ae38 (just to have reproducible test, the run fails on other repositories and revisions as well) and running the scanner. The scanner scans everything and gets stuck with the last console log being `2024-10-25 07:58:28.902 [DefaultDispatcher-worker-13] [traceId=8d946210-b405-4d74-8170-942e3508ec8a, ortRunId=3, component=scanner-worker, scannerJobId=3] level=INFO  kotlinx.coroutines.CoroutineScope - Creating file list for provenance 64 of 366.`. The scan works on the commit before.

The bug doesn't seem to affect very small repositories, for example https://github.com/vdurmont/semver4j.git is not affected.

**Comment by sschuberth** [comment]
@nnobelis, any idea what might have caused this? Could we revert our commit until the issue is fixed?

**Comment by mmurto** [comment]
Removing the [`withContext` here](https://github.com/eclipse-apoapsis/ort-server/blob/19b808bcb166acaa83d9f20bdaf932145e697ca1/storage/spi/src/main/kotlin/Storage.kt#L143-L145) seems to make it work, but I have no idea what it does.

**Comment by sschuberth** [comment]
@nnobelis, could you maybe explain in more detail *why* exceptions would be swallowed without the context switch?

**Comment by nnobelis** [comment]
See my comment on https://github.com/eclipse-apoapsis/ort-server/pull/1303#issuecomment-2441126263.

**Comment by mmurto** [comment]
Fixed by #1317.
