### ISSUE TITLE
UI: Add timezone to timestamps

### ISSUE THREAD

**Issue by wkl3nk** [eclipse-apoapsis/ort-server#1366]
As a user of the web UI, I want all timestamps to carry a hint on which timezone they are based on in order to have total transparency and avoid any confusion with timestamps in UTC. 
Additionally, I would also be interested in a representation of the timestamp in UTC format, in case I have to compare with timestamps in log files etc.
If timestamps are **not** translated into some local timezone, they should be somehow marked to make it transparent that they are UTC.

**Comment by sschuberth** [comment]
I propose to solve this by adding tool-tips in UTC format to all (local) times.

**Comment by Etsija** [comment]
#1374 should resolve this as per Sebastian's proposal.

**Comment by Etsija** [comment]
GitHub once again didn't auto-close this.
