### ISSUE TITLE
Run form should expand and maybe scroll to invalid field on validation error

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#1383]
If there's a validation error in the create run form in some of the collapsed accordions, the form just refuses to submit on clicking the submit button, but any information that an error exists is hidden inside the collapsed accordion. The error should somehow be made visible.

**Comment by Etsija** [comment]
I'm just wondering how...

**Comment by mmurto** [comment]
> I'm just wondering how...

Start from [here](https://react-hook-form.com/docs/useform#shouldFocusError).

**Comment by Etsija** [comment]
With #1412 merged, the validation errors with their corresponding paths are now printed out above the submit button, and the corresponding sub-forms (accordions) are opened in the UI, so this can be closed.
