### ISSUE TITLE
Markdown rendering of code blocks broken in light theme

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#1519]
When the how-to-fix text of a rule violation contains code blocks they are always using a dark theme, making them unreadable when the UI is using the light theme:

![image](https://github.com/user-attachments/assets/df49fdfd-1167-46e6-9f9e-4ff8044cb5c6)

**Comment by Etsija** [comment]
@mnonnenmacher can you copy-paste the markdown message string as-is? I would need to know how the markdown marks a code block.

**Comment by Etsija** [comment]
@mnonnenmacher  Could you please check if #1524 fixes it for you?

**Comment by Etsija** [comment]
Once again didn't autoclose.

**Comment by Etsija** [comment]
No comments received, and I checked from "real world" runs that this is fixed for now, so let's close it.

**Comment by mnonnenmacher** [comment]
@Etsija Yes, it's working, thanks!
