### ISSUE TITLE
UI: Breadcrumbs navigation not working as expected

### ISSUE THREAD

**Issue by MarcelBochtler** [eclipse-apoapsis/ort-server#1520]
Since the change in the PR https://github.com/eclipse-apoapsis/ort-server/pull/1470, the breadcrumb navigation does not work as expected:

![grafik](https://github.com/user-attachments/assets/5699e4f7-575d-4f24-ae88-f24594f5f0cc)

Expected:
Clicking on the repository URL, should navigate to the list of runs for this repository.

Actual:
Clicking on the repository URL navigates to the last scan, which in this case was 1061, so my click did just reload the same page I was already on.

**Comment by sschuberth** [comment]
> Clicking on the repository URL, should navigate to the list of runs for this repository.

@mmurto and I actually discussed this internally in the context of #1470, and I came to the same conclusion that navigating to the runs list would make more sense here. It just didn't make it into the initial implementation.
