### ISSUE TITLE
ORT Server version information is wrong

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#1610]
Although the latest [tag](https://github.com/eclipse-apoapsis/ort-server/tags) is 0.1.0-RC6, both the recently published images and the UI display something prefixed with "0.0.1-RC.001..."

![image](https://github.com/user-attachments/assets/2534d21e-d802-4f1e-ada7-906fcd14c729)

![image](https://github.com/user-attachments/assets/01ed3f81-a29d-47b8-8eb2-419d96163df0)

The SHA1s seem to be recent, though.

**Comment by mnonnenmacher** [comment]
The tagged images at least show the correct versions, e.g.:
```
ORT Server: 0.1.0-RC6
ORT Core: 42.0.0
```

**Comment by sschuberth** [comment]
> The tagged images at least show the correct versions

Sorry, *where* exactly are these correct versions shown?

**Comment by mnonnenmacher** [comment]
> > The tagged images at least show the correct versions
> 
> Sorry, _where_ exactly are these correct versions shown?

In the UI about screen.

**Comment by sschuberth** [comment]
> In the UI about screen.

Ah, ok. So it's correct (for you) when using a tagged image exactly. It's probably wrong for us when deploying `main` as we probably to not fetch tags along with the branch, so that the version can be calculated correctly relative to the latest tag.

**Comment by mnonnenmacher** [comment]
I just tested with the most recent image and see the same image. Could the fix be to make sure that the Docker build job fetches the tags from the repository? Because my local builds work correctly.

**Comment by sschuberth** [comment]
> Could the fix be to make sure that the Docker build job fetches the tags from the repository?

I guess so, yes.
