### ISSUE TITLE
Make the local port for Docker compose easily configurable

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#173]
Currently the Docker compose setup hard-codes the local port to 8080. This default port conflicts e.g. with a locally running Jenkins. Thus, it would be nice if the local port to use could be overridden, preferably without the need to change any files committed to Git, like by setting an environment variable or so.

**Comment by mnonnenmacher** [comment]
I've assigned this to myself as I'm working on a similar task related to choosing the Docker images.

**Comment by sschuberth** [comment]
This was fixed as part of https://github.com/eclipse-apoapsis/ort-server/pull/175.
