### ISSUE TITLE
Renovate's PRs do not always include all updates they say they do

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#215]
> I wonder why the PR says that it's updating to v1.31.26, but the commit says v1.31.24, which seems to be the version updated to based on the lockfile. The fix for #209 is included in 1.31.24, but still the discrepancy is a little strange. Looks as if when new versions have been released after Renovate has created this PR, it has changed the title and text, but kept the commit the same.

_Originally posted by @mmurto in https://github.com/eclipse-apoapsis/ort-server/issues/212#issuecomment-2102621439_

It could make sense to double check Renovate's config.

**Comment by mnonnenmacher** [comment]
So far I saw this happening only once but there were several PRs were Renovate correctly updated the commit when a new version was released before it got merged. I think as long as we don't see this happening again it's not worth investigating.

**Comment by mmurto** [comment]
> So far I saw this happening only once but there were several PRs were Renovate correctly updated the commit when a new version was released before it got merged. I think as long as we don't see this happening again it's not worth investigating.

Probably not worth tracking, let's reopen if it resurfaces.

**Comment by mnonnenmacher** [comment]
For reference, it happened again in #259 (title claims an update to 3.4.2 but the commit only updates to 3.4.1).

**Comment by mmurto** [comment]
Saw it happen with #228 as well.
