### ISSUE TITLE
Ort docker image build fails

### ISSUE THREAD

**Issue by AnishaM7** [eclipse-apoapsis/ort-server#229]
Ort docker image build fails
- docker build workers/analyzer/docker -f workers/analyzer/docker/Analyzer.Dockerfile -t ort-server-analyzer-worker-base-image

![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/070b62b4-9425-43cd-8cf7-f40eb7cb078e)

**Comment by sschuberth** [comment]
The error message says that the host https://download.swift.org/ is not reachable from your machine, though for me that host works fine. So it's probably some (corporate) proxy setup thing on your side.

**Comment by AnishaM7** [comment]
Hi @sschuberth , Thanks for the hint.

Can you please provide link to documentation on how t proceed once the UI is up

**Comment by sschuberth** [comment]
> Can you please provide link to documentation on how t proceed once the UI is up

There is no such documentation yet to the best of my knowledge. This project is still very young, esp. the UI part, so we expect people to scratch their own itch and the community to contribute whatever documentation they feel lacking 😉 

As your original problems seems to be resolved, please consider closing this issue and opening another one if you have other (follow-up) issues.

**Comment by mnonnenmacher** [comment]
@AnishaM7 Please reopen this issue if you still have the same error while building the analyzer image.
