### ISSUE TITLE
No way to pass in URLs for ORT configuration files?

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#260]
We are currently hosting our ORT configuration (`config.yml`, `license-classifications.yml`, `evaluator.rules.kts`) in a GitHub repository. It is not clear whether these can be "fed" into ORT Server job configuration as URLs, but the code suggests these need to be local files only:
```
    /**
     * The path to the license classifications file which is resolved from the configured configuration source. If this
     * is null, the default path from ORT will be used.
     */
    val licenseClassificationsFile: String? = null,
```
If this is the case, it would be great if the configuration could also be specified optionally with the URLs of the corresponding files, not only local paths.

**Comment by sschuberth** [comment]
> in a GitHub repository.

I believe that's what the [GitHub config file provider](https://github.com/eclipse-apoapsis/ort-server/tree/main/config/github) is there for.

**Comment by Etsija** [comment]
Oh, yes, thanks!
