### ISSUE TITLE
Improvements for Repository index page

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#291]
From 23.5.2024 front-end alignment meeting:

- [x] add Created At date for each ORT run in the list - issue #284
- [x] no mouse click pointer for job traffic lights indicators
- [x] for ACTIVE state, use animate-pulse class to better indicate which job is currently active
- [x] change the colour class of SCHEDULED state eg. into lighter blue / cyan, to make a clear distinction from a future state "FINISHED WITH WARNINGS"
- [x] sorting, filtering, pagination of the ORT runs will be coming in another PR. See also issue #285

**Comment by Etsija** [comment]
@mnonnenmacher I edited the issue and deleted the done improvements from the list. Is it OK to leave this still open as a "bookmark" issue for further improvements to the Repository index page, or rather close this and later on, create a separate issue for sorting, filtering, pagination?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher I edited the issue and deleted the done improvements from the list. Is it OK to leave this still open as a "bookmark" issue for further improvements to the Repository index page, or rather close this and later on, create a separate issue for sorting, filtering, pagination?

Instead of deleting items better use a task list (I have converted the description to show what I mean). That better documents progress.
