### ISSUE TITLE
Create a Rerun functionality for each ORT Run

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#294]
While we are missing a "default run configuration" concept from ORT Server, it would be useful to have a "Rerun" button for each ORT Run of a Repository.  

By clicking the button, an ORT Run creation page would open, pre-filled with the job configurations of the Run for which the Rerun button was pushed. This would be a quick way for the user to recreate an ORT Run based on an earlier run configuration, and not going through the trouble of redefining all job parameters.

**Comment by mnonnenmacher** [comment]
Related to #206.
