### ISSUE TITLE
"pnpm dev" doesn't work anymore after PR #297

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#311]
After PR #297, `pnpm dev`, followed by going to http://localhost:5173, leads to this, instead of Keycloak sign-in page, so the UI cannot be started in dev mode. If the process of building a dev UI was changed, this isn't shown in the UI documentation.
![Capture](https://github.com/eclipse-apoapsis/ort-server/assets/599904/ba04f882-fff6-4a36-96c8-2d8fa7cb81bd)

At least I _think_ it was #297 that broke it, as it changed master-realm file.  I am running the server as before, `docker compose pull && docker compose up`, followed by `./gradlew :core:generateApiSpec` and `pnpm build`, so should I additionally run some Gradle tasks to fix this?

**Comment by mnonnenmacher** [comment]
You might have to recreate the Keycloak service, e.g. with `docker compose up -d --force-recreate keycloak`.

**Comment by Etsija** [comment]
That didn't work either. I need to consult our team as to how to fix this, as if I can't run the UI in dev mode, I can't verify your #315 either.

**Comment by Etsija** [comment]
I also tried to stop and recreate all containers with `docker compose up -d --force-recreate`, but still, the Keycloak service isn't updated.
```
quay.io/keycloak/keycloak                              24.0.4     c8bfd0bc98f0   2 weeks ago     458MB
quay.io/keycloak/keycloak                              24.0.3     959cb27d37ae   3 weeks ago     458MB
```

**Comment by Etsija** [comment]
That didn't work. Removing the Keycloak image from my local docker setup, then `docker compose pull & docker compose up -d` ends up with 2 weeks old Keycloak image, which upon login gives me the above error message.  What would be the specific steps to completely regenerate the Keycloak service? Couldn't find anything from the documentation.

**Comment by Etsija** [comment]
Tried also to compile everything locally with
```
./gradlew buildAllImages
```
followed by
```
ORT_SERVER_IMAGE_PREFIX= ORT_SERVER_IMAGE_TAG=latest docker compose up -d
```
Same error, can't log in.

**Comment by lamppu** [comment]
You don't happen to have a .env file with the VITE_CLIENT_ID set up to the previous id?

**Comment by Etsija** [comment]
Nice catch!  That was indeed the reason!  Closing now, as this is solved.
