### ISSUE TITLE
Document the commit convention of the project

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#319]
ORT Server project currently uses a commit convention that looks like [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), but the convention does not semantically adhere to Conventional Commits. As an example, [`feat` types are used for development environment commits](https://github.com/eclipse-apoapsis/ort-server/commit/33504d47c5802662eed33215a7d8d5039e28dcdc), which would lead to a `MINOR` version change in Semantic Versioning if using the tooling around Conventional Commits/Semantic Versioning, and this does not make sense, as nothing in the application changed in the example commit.

It would be good to decide and document the commit convention.

**Comment by sschuberth** [comment]
> this does not make sense, as nothing in the application changed in the example commit.

You're right, but I believe this was simply an oversight. The type should probably have been `doc` or the like. So essentially, I believe the goal *is* to adhere to CC fully. But let's see what @mnonnenmacher as the project lead says.

**Comment by mmurto** [comment]
> You're right, but I believe this was simply an oversight. The type should probably have been `doc` or the like. 

Yep, I didn't think of it at all when making the commit, so absolutely an oversight. :D

**Comment by sschuberth** [comment]
> Yep, I didn't think of it at all when making the commit

I didn't even realize you're referring to your own commit, but was assuming it would refer to [this](https://github.com/eclipse-apoapsis/ort-server/pull/318#issuecomment-2137118444) discussion 😸

**Comment by mnonnenmacher** [comment]
The initial [CONTRIBUTING.md](https://github.com/eclipse-apoapsis/ort-server/blob/main/CONTRIBUTING.md) has a section for this now, but the documentation for the usage of conventional commit types still needs to be improved.

**Comment by mnonnenmacher** [comment]
Also the documentation should clearly describe what kind of change should be marked as a breaking change.
