### ISSUE TITLE
Issue with Ort ui setup

### ISSUE THREAD

**Issue by AnishaM7** [eclipse-apoapsis/ort-server#325]
Hi Team,
We are trying to setup ort server using docker-compose.
In web-ui documentation, we deployed it locally,we see the below error.
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/45de4972-2540-4321-8d83-80d37c64bfb6)

**Comment by Etsija** [comment]
Can you list your VITE_ environment variables?

**Comment by mnonnenmacher** [comment]
Closed due to lack of feedback.
