### ISSUE TITLE
How to configure clients in Keyclock

### ISSUE THREAD

**Issue by AnishaM7** [eclipse-apoapsis/ort-server#326]
Hi Team,

we have setup ort-server using docker compose.
In our keyclock set up there are some clients by default.

Please let us know if we should create additional clients with particular role to access the ort server

or Which client can login to ort server api
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/c78689c0-f146-4484-ba7d-dcdff007415d)

If we have to create new client, please let us know values for these parameters
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/0aba5ee1-0a1e-42f9-a335-921c4e0718d0)

**Comment by mnonnenmacher** [comment]
Please have a look at the preconfigured clients in the Keylcoak instance that is started by our `docker-compose.yml`. It currently creates three clients:
* ort-server: This client is used for direct API access.
* ort-server-ui: This client is used for the UI.
* ort-server-ui-dev: This client is used for UI development.

If you want to use your own Keycloak instance you need to configure clients similar to the first two.

**Comment by AnishaM7** [comment]
Hi @mnonnenmacher, Thank you for responding 

For Ort-server APi which credentails should we pass
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/fcb35385-ca57-4d37-8f6b-b5d7ada800ac)

Ort UI still shows 
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/142e1755-09ff-4f0d-9b4a-d6c3a8771a09)
can you pls guide me, how to login to this

**Comment by mnonnenmacher** [comment]
Can you please provide a few more details about your setup? Are you running the Docker Compose script as provided in this repository or have you done changes? Are you trying to log in via the UI run by Docker Compose or did you start it with `pnpm dev`? In both cases the Keycloak login form should not ask you for the client id and secret. Or are you trying to log in with a REST client like Postman?

**Comment by AnishaM7** [comment]
We use docker-compose to start the ort-server. 
We are not sure how to login to UI
We have  keyclock, UI, ORT server API services.

When we try to access the ORT UI,(deployed with docker-compose) , UI only displays Unable to login message
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/5898fd5f-5e12-47ba-bdba-99e5a97c8fa3)
It is not clear how can we login to ort-UI

When we try to access ORT server API, we have to authrize
![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/b2fca2ce-6c71-4465-b82f-9ad2b0d9edb0)
We are not sure what is the value for client ID and client secret

**Comment by haikoschol** [comment]
@AnishaM7 A while ago, I tried to figure out what parameters/roles/scopes/clients/users/etc. need to be added to Keycloak to make ORT Server work with it. You can find my attempt in #237. I tried diffing the realm JSON from the Docker compose setup with an unmodified realm export, but that wasn't as helpful as I hoped.

Unfortunately I don't have time to work on it right now. Maybe you have time and determination to fiddle with it until it works? :)

**Comment by Etsija** [comment]
I noticed at least something that needs to be probably fixed [here](https://github.com/eclipse-apoapsis/ort-server/blob/b154319d3aef54c329454520ef40a212a757614b/ui/src/components/providers.tsx#L30-L36):
- earlier on, we only had the "dev" environment for the UI available, so in case the `VITE_` environment variables are not provided, this code defaults to the dev settings
- now as the UI has been dockerized, we should default to the Docker Compose settings instead
- moreover, it is specified [here](https://github.com/eclipse-apoapsis/ort-server/tree/main/ui#docker) that `VITE_API_URL` should be `http://localhost:8080/api/v1`. However, that is a bit conflicting as I am seeing that in our code, it's defaulting to http://localhost:8080 instead

**Comment by mnonnenmacher** [comment]
> moreover, it is specified [here](https://github.com/eclipse-apoapsis/ort-server/tree/main/ui#docker) that VITE_API_URL should be http://localhost:8080/api/v1. However, that is a bit conflicting as I am seeing that in our code, it's defaulting to http://localhost:8080/ instead. [See also this](https://github.com/eclipse-apoapsis/ort-server/blob/b154319d3aef54c329454520ef40a212a757614b/ui/docker/entrypoint.sh#L29-L31)

@Etsija That was just wrong in the docs, I made #339 to fix that. It actually uses `http://localhost:8080` as default.

> now as the UI has been dockerized, we should default to the Docker Compose settings instead

@Etsija That's not necessary, the `entrypoint.sh` used in the Docker image applies the values required for Docker Compose so that the defaults work for the dev environment.

> We are not sure what is the value for client ID and client secret

@AnishaM7 The authentication in the Swagger UI is unfortunately broken and needs to be fixed. Please try to run the following commands and check if the login at `http://localhost:8082` works afterward:

```
docker compose pull
docker compose up --force-recreate
```

**Comment by AnishaM7** [comment]
Hi @mnonnenmacher,
Executed below commands,

docker compose pull
docker compose up --force-recreate
UI still shows unable to login error
http://localhost:8082

![image](https://github.com/eclipse-apoapsis/ort-server/assets/62882541/4714d78e-1998-4737-bd29-5caa3675bfca)

**Comment by mnonnenmacher** [comment]
@AnishaM7 Is this still an issue for you or could you solve it in the meantime?

**Comment by mnonnenmacher** [comment]
Closed due to lack of feedback.

@AnishaM7 Please reopen the issue or create a new one if you still have issues with the UI.
