### ISSUE TITLE
Unexpected config values for Scaleway Secret Provider

### ISSUE THREAD

**Issue by haikoschol** [eclipse-apoapsis/ort-server#389]
We are running ORT Server core in a `Deployment` in Scaleway Kubernetes. In order to use the Scaleway Secret Provider, we've set the following environment variables:
```
- name: SCW_API_VERSION
  value: "v1beta1"
- name: SCW_REGION
  value: "nl-ams"
```

A `GET` request to `/api/v1/organizations/<id>/secrets` fails with an internal server error and this message in the logs:
```
Caused by: com.typesafe.config.ConfigException$BadValue: hardcoded value: Invalid value at 'scwApiVersion': The enum class ScalewayApiVersion has no constant of the name 'v1beta1' (should be one of [V1_ALPHA1, V1_BETA1].)
```

The request succeeds with setting `SCW_API_VERSION` to `V1_BETA1` and `SCW_REGION` to `NETHERLANDS_AMSTERDAM`. 

Is this intended behavior? To me [the code](https://github.com/eclipse-apoapsis/ort-server/blob/c355916e6f848f3abaa6a95f15b0d38ccf022ff7/secrets/scaleway/src/main/kotlin/ScalewayConfiguration.kt#L77) looks like `v1beta1` and `nl-ams` should work. Or am I misunderstanding what `@SerialName` does?

cc @sschuberth

**Comment by sschuberth** [comment]
> Is this intended behavior?

Yes. For type safety, I decided to require enum names instead of the untyped strings the raw REST API URL uses.

**Comment by haikoschol** [comment]
It would be nice to use the same strings as Scaleway does in their documentation. But if that results in a less helpful error message for incorrect values, it's probably not an improvement.

**Comment by sschuberth** [comment]
> It would be nice to use the same strings as Scaleway does in their documentation.

Let me check if I could easy support both, enum names and raw strings as values.

**Comment by sschuberth** [comment]
@mnonnenmacher auto-close also did not work here. Could you contact EF support to check whether it's some issue with [Otterdog](https://otterdog.readthedocs.io/en/stable/)?

**Comment by haikoschol** [comment]
> > It would be nice to use the same strings as Scaleway does in their documentation.
> 
> Let me check if I could easily support both, enum names and raw strings as values.

Works now. Thanks!

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher auto-close also did not work here. Could you contact EF support to check whether it's some issue with [Otterdog](https://otterdog.readthedocs.io/en/stable/)?

This is really weird, I could not find any bug reports that the feature is broken for anyone else and it also seem there is no option to configure it somehow. But I will create an issue with EF eventually.
