### ISSUE TITLE
Add endpoint to get issues of ORT run

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#405]
Add an endpoint to get the issues of an ORT run. This should include issues created by the server as well as issues created by the ORT tools.

The location of the endpoint should be "/runs/{id}/issues" (see #406).

**Comment by sschuberth** [comment]
> This should include issues created by the server as well as issues created by the ORT tools.

The latter was implemented in https://github.com/eclipse-apoapsis/ort-server/pull/1014, but it still [lacks](https://github.com/eclipse-apoapsis/ort-server/pull/1014#issuecomment-2368837895) "ORT Run issues for the Service".
