### ISSUE TITLE
Consolidate API endpoints for ORT runs

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#406]
The endpoints to get information about ORT runs are currently at two different locations:

* `/repositories/{id}/runs/{index}`
* `/runs/{id}/reporter/{filename}`
* `/runs/{id}/logs`

Move the first endpoint to `/runs/{id}` to make the API more consistent.

**Comment by wkl3nk** [comment]
I agree, ```/runs/{id}```sounds reasonable and consistent.

**Comment by oheger-bosch** [comment]
Yes, it makes sense to have the run-related information under the path `/runs`.

Just wondering how to treat the `/repositories/{id}/runs` endpoint that returns the runs of a specific repository. Should it stay as is or be moved, too, maybe to something like `/runs/repository/{id}` ?

**Comment by mnonnenmacher** [comment]
> Just wondering how to treat the `/repositories/{id}/runs` endpoint that returns the runs of a specific repository. Should it stay as is or be moved, too, maybe to something like `/runs/repository/{id}` ?

I would leave that where it is, it's consistent with other endpoints that return associated objects like `organizations/{id}/products` or `repositories/{id}/secrets`.

**Comment by mmurto** [comment]
> > Just wondering how to treat the `/repositories/{id}/runs` endpoint that returns the runs of a specific repository. Should it stay as is or be moved, too, maybe to something like `/runs/repository/{id}` ?
> 
> I would leave that where it is, it's consistent with other endpoints that return associated objects like `organizations/{id}/products` or `repositories/{id}/secrets`.

Another option would be to expose them from `/runs` by taking in a filter parameter (query/body, not path) for `repositoryId`.

**Comment by mnonnenmacher** [comment]
> Another option would be to expose them from /runs by taking in a filter parameter (query/body, not path) for repositoryId.

That's an option, but it's harder to implement because the permission model is based on organizations, products, and repositories, so filtering the full list of runs by permission requires a lot of permission checks and in my opinion it's not worth it if we don't have a real use case for it. Filtering is straight forward if the repository is known in advance.

After looking a bit deeper into the topic I decided that moving the endpoint altogether makes things unnecessarily complicated for the frontend where the repository id and ORT run index are known from path parameters, but not the run id. Instead, I have changed #425 to only add the new endpoint at `/rund/{id}` as this is useful for other scenarios, but not remove the old endpoint at `/repositories/{id}/runs/{index}`.

**Comment by mmurto** [comment]
> > Another option would be to expose them from /runs by taking in a filter parameter (query/body, not path) for repositoryId.
> 
> That's an option, but it's harder to implement because the permission model is based on organizations, products, and repositories, so filtering the full list of runs by permission requires a lot of permission checks and in my opinion it's not worth it if we don't have a real use case for it. Filtering is straight forward if the repository is known in advance.

Makes sense, if there are no use-cases.

> After looking a bit deeper into the topic I decided that moving the endpoint altogether makes things unnecessarily complicated for the frontend where the repository id and ORT run index are known from path parameters, but not the run id. Instead, I have changed #425 to only add the new endpoint at `/rund/{id}` as this is useful for other scenarios, but not remove the old endpoint at `/repositories/{id}/runs/{index}`.

`GET /api/v1/repositories/{repositoryId}/runs` returns both the run ID and index if I read the spec correctly, so `/runs/{id}` should work for it as well.

**Comment by mnonnenmacher** [comment]
> `GET /api/v1/repositories/{repositoryId}/runs` returns both the run ID and index if I read the spec correctly, so `/runs/{id}` should work for it as well.

Yes, but if you open the page at `/organizations/{id}/products/{id}/repositories/{id}/runs/{index}` the frontend only knows about the `index`, so it seemed convenient to me to keep the existing endpoint as we already have the code anyway.

However, I just noticed that if you open such a link directly in the browser the frontend currently loads the homepage instead of the run details page, I don't thank think that's how it's supposed to be, shall I create an issue?

**Comment by mmurto** [comment]
> > `GET /api/v1/repositories/{repositoryId}/runs` returns both the run ID and index if I read the spec correctly, so `/runs/{id}` should work for it as well.
> 
> Yes, but if you open the page at `/organizations/{id}/products/{id}/repositories/{id}/runs/{index}` the frontend only knows about the `index`, so it seemed convenient to me to keep the existing endpoint as we already have the code anyway.

Yeah, no need to remove it quickly and even though ids generally make more sense to me, using index may be the right choice here. If we think we should use ids at some point, the route needs to be changed to `/organizations/{id}/products/{id}/repositories/{id}/runs/{runId}`

> However, I just noticed that if you open such a link directly in the browser the frontend currently loads the homepage instead of the run details page, I don't thank think that's how it's supposed to be, shall I create an issue?

Yep, users should be able to navigate directly to URL, not only via links, so it's a bug.

**Comment by mnonnenmacher** [comment]
> Yeah, no need to remove it quickly and even though ids generally make more sense to me, using index may be the right choice here. If we think we should use ids at some point, the route needs to be changed to `/organizations/{id}/products/{id}/repositories/{id}/runs/{runId}`

I have a strong preference for indexes because they carry a meaning: `.../runs/5` tells you that this was the fifth run for the repository and you know that `.../runs/4` was the previous run. You could not tell that from the global ids.

> Yep, users should be able to navigate directly to URL, not only via links, so it's a bug.

#435

**Comment by mmurto** [comment]
> > Yeah, no need to remove it quickly and even though ids generally make more sense to me, using index may be the right choice here. If we think we should use ids at some point, the route needs to be changed to `/organizations/{id}/products/{id}/repositories/{id}/runs/{runId}`
> 
> I have a strong preference for indexes because they carry a meaning: `.../runs/5` tells you that this was the fifth run for the repository and you know that `.../runs/4` was the previous run. You could not tell that from the global ids.

Makes sense to me.

**Comment by oheger-bosch** [comment]
> > I have a strong preference for indexes because they carry a meaning: `.../runs/5` tells you that this was the fifth run for the repository and you know that `.../runs/4` was the previous run. You could not tell that from the global ids.
> 
> Makes sense to me.

Are you sure that indices are really that meaningful? Consider the case of a large project that integrates ORT runs into their PR checks. Then you have succeeding runs on many different branches, and the information that run 5 was the successor of run 4 is rather useless.
