### ISSUE TITLE
Add a set of test data to seed local test databases with

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#422]
We should have a set of data to seed database with to easily develop against. We should also have a script that automatically seeds the development Docker Compose database with the seed data.

Relates to https://github.com/eclipse-apoapsis/ort-server/pull/72#pullrequestreview-2118023945

**Comment by sschuberth** [comment]
Is this actually different from https://github.com/eclipse-apoapsis/ort-server/issues/1318?

**Comment by mmurto** [comment]
Nope.
