### ISSUE TITLE
Add pagination to lists

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#453]
The lists of organizations, products, repositories, and runs use the default limit of 20 items. If there are more entries, they are currently not visible.

Add support for pagination to all lists, so that all entries can be accessed.

Note that currently the API responses do not contain the number of pages or the total number of entries, so it would not be possible to show the total number of pages in the UI. Please also document which properties would be required to properly implement pagination so that the API can be improved later on.

**Comment by sschuberth** [comment]
> Please also document which properties would be required to properly implement pagination so that the API can be improved later on.

As @Etsija is currently on vacation, maybe @mmurto can provide some input here.

**Comment by mmurto** [comment]
For pagination adding the total number of rows should be enough - offset seems to be already implemented.

**Comment by mnonnenmacher** [comment]
> For pagination adding the total number of rows should be enough - offset seems to be already implemented.

I saw two different kinds of pagination data in APIs. One used page number, page size and total number of pages, the other offset, limit and total count. The latter would course be easier to implement for us as it requires less changes, but if the first option would be significantly better for the UI code I would be open to change it.

**Comment by mmurto** [comment]
> > For pagination adding the total number of rows should be enough - offset seems to be already implemented.
> 
> I saw two different kinds of pagination data in APIs. One used page number, page size and total number of pages, the other offset, limit and total count. The latter would course be easier to implement for us as it requires less changes, but if the first option would be significantly better for the UI code I would be open to change it.

I don't think exposing page number from the API is required, as page number is pretty much just `offset / limit`. Sure the calculation could be done in the back end, but I don't know if there is value in it.

Another option would be [cursor pagination](https://slack.engineering/evolving-api-pagination-at-slack/), but I think offset should work at least for now.

**Comment by Etsija** [comment]
So we need total number of entries for all GET requests that return lists to paginate, of which I created an issue to back-end.

**Comment by mnonnenmacher** [comment]
@Etsija With #633 all list endpoints should now provide the total entity count.

**Comment by Etsija** [comment]
@mnonnenmacher @sschuberth I'm scanning the status of the older UI tickets, and I think this can be closed now, as all existing list endpoints provide the total entity count, and we have implemented pagination for all pages that use list endpoints. There are some list endpoints not yet implemented, like `.../{runId}/issues` but I believe you will provide the total entity count for those in the future?
