### ISSUE TITLE
UI: Enable the configuration of the VCS path when starting a run

### ISSUE THREAD

**Issue by MarcelBochtler** [eclipse-apoapsis/ort-server#502]
The UI is currently missing the feature to configure the VCS path when starting an ORT run.
This also means that reruns of runs triggered like this, will produce a different result:
```json
{
  "revision": "main"
  "path": "npm/simple",
  "jobConfigs": {
    ...
  }
}
```

**Comment by Etsija** [comment]
@MarcelBochtler @mnonnenmacher Seems like this is now implemented, and I verified from the code that the path is properly taken into the run configuration, so can this issue be closed now?

**Comment by mnonnenmacher** [comment]
> @MarcelBochtler @mnonnenmacher Seems like this is now implemented, and I verified from the code that the path is properly taken into the run configuration, so can this issue be closed now?

It's weird that autoclose in this repository sometimes works and sometimes doesn't.
