### ISSUE TITLE
Move delete buttons for organizations, products, and repositories to settings

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#529]
Move the delete functionality for organizations, products, and repositories to a new settings tab, similar to the "Danger Zone" in the GitHub repository settings. Deleting one of these entities should never happen accidentally as it could delete important data that cannot be recovered, so the alert dialog should require additional verification like typing out the entity name.

**Comment by sschuberth** [comment]
To me, moving the buttons and additional verification in the alert dialog are two different things. Do we really need to implement both, or is only the latter probably enough?

**Comment by mnonnenmacher** [comment]
To me deletion is a rare operation that should not be prominently shown on the default page but rather be hidden in the settings.

**Comment by mmurto** [comment]
> To me deletion is a rare operation that should not be prominently shown on the default page but rather be hidden in the settings.

I agree with this, spending screen real estate on something probably done so seldomly is not the best use of space.

**Comment by sschuberth** [comment]
> is not the best use of space.

Which we have plenty of, though.

**Comment by Etsija** [comment]
Well what about editing of the said items: should that also be hidden in the settings?

**Comment by mnonnenmacher** [comment]
> Well what about editing of the said items: should that also be hidden in the settings?

On the long term, probably yes. But to me not urgent at all.

**Comment by sschuberth** [comment]
> Well what about editing of the said items: should that also be hidden in the settings?

Relates to https://github.com/eclipse-apoapsis/ort-server/issues/831.
