### ISSUE TITLE
No logs about authentication errors from GitHub config file provider

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#532]
Currently, when setting up the GitHub configuration file provider with wrong bearer token, there are no ERROR messages about the failure to authenticate in the server log. Instead, there are ConfigExceptions coming from either [this](https://github.com/eclipse-apoapsis/ort-server/blob/2946f0c099edd65ea201ca7949f818a26c75d557/config/github/src/main/kotlin/GitHubConfigFileProvider.kt#L212) or [this](https://github.com/eclipse-apoapsis/ort-server/blob/2946f0c099edd65ea201ca7949f818a26c75d557/config/github/src/main/kotlin/GitHubConfigFileProvider.kt#L218) line, which is confusing, as the exceptions don't immediately tell the user that authorization with the GitHub REST API has failed.

I think `resolveContext()` of `GitHubConfigFileProvider` could be improved to include some helpful logs in case of auth failures. @oheger-bosch do you see any possibilites for such improvements? In my case, I just spent several hours of debugging why the branch or SHA-1 aren't found from our config repository, only to find out that I had copied wrong bearer token to the secrets, so the server couldn't access the repository at all.

**Comment by oheger-bosch** [comment]
I have added checks for the response status of GitHub requests and better log and exception messages.
