### ISSUE TITLE
Include run ID in all log rows caused by the run

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#569]
Log rows like `2024-07-02 11:12:48.824 [pool-1-thread-4] level=INFO  org.ossreviewtoolkit.evaluator.Rule - 	Rule skipped.` would be much more useful if logging always printed the run ID.

**Comment by sschuberth** [comment]
That's probably a bit hard to get done for log statements that come from third-parties (like the one you quoted, which comes from ORT core, which knows nothing about ORT server run IDs).

**Comment by mmurto** [comment]
Do ORT Server and ORT core use the same logging library? If so, I wonder if it has an ability to add trace IDs somehow to be used for all calls no matter the depths - some log libraries with other languages I've used have that kind of ability.

**Comment by mnonnenmacher** [comment]
The problem with MDC is that it attaches the context to threads using Java's ThreadLocal and it isn't clear if that plays well with coroutines. It's something that needs to be tested but no one had time for that so far.

At least Ktor seems to support MDC so maybe it works: https://ktor.io/docs/server-call-logging.html#mdc

**Comment by sschuberth** [comment]
> Do ORT Server and ORT core use the same logging library?

Both use [logback](https://logback.qos.ch/), which has its own [MDC docs](https://logback.qos.ch/manual/mdc.html).

**Comment by mmurto** [comment]
Great! I think some work would also be needed to transmit the MDC over all the communication methods, at least the transporters, like RabbitMQ and Kubernetes Jobs. Do the services make HTTP calls between them, or do they communicate purely through the transports?

**Comment by mnonnenmacher** [comment]
Kotlin Coroutines has support for the SLF4J MDC: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-slf4j/kotlinx.coroutines.slf4j/-m-d-c-context/
This is likely what the Ktor MDC support mentioned above uses.

Another library I find very interesting is Klogging: https://klogging.io/
It has a nice API to add values from templates directly to the structured logs without additional code and is also integrated with SLF4J and Ktor.

For the goal to have the run and trace IDs be part of all logs I expect that both of the above solutions would work, but someone needs to give it a try.

**Comment by mnonnenmacher** [comment]
I did some testing with MDC in ORT itself and applied some fixes here: https://github.com/oss-review-toolkit/ort/pull/9006

Once this is released, I will test adding values like the ORT run id or the trace ID to the MDC context in the server and hopefully it should then appear in all related logs, also from third-party code.

**Comment by sschuberth** [comment]
As https://github.com/oss-review-toolkit/ort/pull/9006 has been merged, do you want me to do an early ORT release to speed things up?

**Comment by mnonnenmacher** [comment]
> As [oss-review-toolkit/ort#9006](https://github.com/oss-review-toolkit/ort/pull/9006) has been merged, do you want me to do an early ORT release to speed things up?

Yes, please, then I could start with the testing tomorrow.
