### ISSUE TITLE
Add progress indicators to UI

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#578]
Loading the lists of entities in the UI can sometimes take several seconds, especially for the list of ORT runs. As there is no visual feedback while loading the data, it is unclear to the user if the click worked or not until the result appears.

To improve this, show some progress indicator while the data is being loaded.

**Comment by sschuberth** [comment]
Shouldn't we instead do https://github.com/eclipse-apoapsis/ort-server/issues/453?

**Comment by mnonnenmacher** [comment]
> Shouldn't we instead do #453?

Both should be done. Slow requests can always happen, even if less entities are returned.

**Comment by mmurto** [comment]
For anyone wanting to take a stab at this, a good start could be to add a [pending component](https://tanstack.com/router/latest/docs/framework/react/guide/data-loading#showing-a-pending-component) to the relevant routes, like the [repo page](https://github.com/eclipse-apoapsis/ort-server/blob/3bc24b3415b17a768fac29eb2988135d6dcc2163/ui/src/routes/_layout/organizations/%24orgId.products.%24productId.repositories.%24repoId.index.tsx#L308-L332).

**Comment by Etsija** [comment]
Found the pending component this morning, so I will.
