### ISSUE TITLE
DEP5 probably causes Reuse workflow to not check for anything

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#58]
This wildcard in dep5 probably causes Reuse to consider all files to be valid even without any license headers, as the [matcher is not real glob](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#files-field).

https://github.com/eclipse-apoapsis/ort-server/blob/8035d3dffb8d8b11c7899a888cd1eb2fa823ee40/.reuse/dep5#L7-L9

**Comment by sschuberth** [comment]
> even without any license headers

I guess that's more or less the point: You only need to add those files to `dep5` that do not come with a license header. That said, I tend to agree that the pattern is probably too wide and might shade future files being added.

**Comment by mmurto** [comment]
To be clear, dep5 uses simplified glob, so `*` matches every file in the repository, so Reuse will never warn about anything in this repository with that config.

**Comment by sschuberth** [comment]
I'm looking into making it more strict as we speak.

**Comment by sschuberth** [comment]
For some reason this did not auto-close on the merge of https://github.com/eclipse-apoapsis/ort-server/pull/73, so @mmurto could you please close this manually?
