### ISSUE TITLE
Display version info in the UI

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#608]
Display the versions provided by the [new endpoint](https://github.com/eclipse-apoapsis/ort-server/pull/510) in the administrative UI.

**Comment by lamppu** [comment]
Working on this now

**Comment by mnonnenmacher** [comment]
Why show it only to admins and not all authenticated users, as in #95 it was discussed to make the endpoint available to all authenticated users?

**Comment by sschuberth** [comment]
I forgot about the outcome of that discussion; if we can to it for all authenticated users, the better.

**Comment by lamppu** [comment]
Ok, in that case I'm a little uncertain of where to put this information then. Would you like it shown straight in the front page or in some server info dedicated page or something?

**Comment by sschuberth** [comment]
Maybe we should take this as an opportunity to create an "About" screen in addition to "Admin" and display the version information there. At some point we'd want to add more "About"-kind of information, like also the list of used OSS dependencies / attributions, created by our own tooling 😉

**Comment by Etsija** [comment]
I'm seeing version info on About menu, so can this be closed?

**Comment by sschuberth** [comment]
Yes.
