### ISSUE TITLE
Keynames used for the secrets for Package Configuration Provider config instead of values

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#611]
We are using the same secret `dosToken` for both DOS Scanner and DOS Package Configuration Provider to enable the plugins to communicate with DOS back-end.  The secret is defined in Docker Compose in `secrets/compose/secrets.properties` with (an example)
```
# DOS credentials
dosToken=1234567890abcde
```

1. For the Scanner job, the relevant part of the configuration object is
```
scanners: ['DOS'],
config: {
  DOS: {
    options: {
      readFromStorage: 'false',
      writeToStorage: 'true',
      url: 'https://dos/api/url/',
      frontendUrl: 'https://dos/frontend/url/',
      pollInterval: '5',
      timeout: '300',
    },
    secrets: {
      token: 'dosToken',
    },
  },
},
```
The value of `dosToken` is used properly for DOS scanner, which is also verified from PostgresDB from the table `scanner_configuration_secrets`.

2. For the Evaluator job, the relevant part of the configuration object is
```
packageConfigurationProviders: [
  {
    type: 'DOS',
    options: {
      url: 'https://dos/api/url/',
      timeout: '300',
    },
    secrets: {
      token: 'dosToken',
    },
  },
],
```
But we have verified from our back-end that instead of the value of `dosToken`, the server tries to use a literal key `dosToken` as the value, leading to communication failure with DOS back-end.

**Comment by Etsija** [comment]
If the same secret cannot actually be used for two workers, this is not documented.

**Comment by sschuberth** [comment]
> the server tries to use a literal key `dosToken` as the value

I'm very surprised that this is not *always* the case, also for the scanner. Is there maybe some config transformation or so configured for the scanner, that is not configured for the evaluator?

**Comment by haikoschol** [comment]
Looks like the function that resolves `dosToken` to the actual secret is `WorkerContext.resolveConfigSecrets()`. It's called in [`ScannerRunner.run()`](https://github.com/eclipse-apoapsis/ort-server/blob/3ce0109ad0e7654b10859537e6bd81bdc8322fc1/workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt#L57) but not in [`EvaluatorRunner.run()`](https://github.com/eclipse-apoapsis/ort-server/blob/9cac3a0777443c16f7569d4368c2588befd02da3/workers/evaluator/src/main/kotlin/evaluator/EvaluatorRunner.kt#L67).

**Comment by Etsija** [comment]
> Looks like the function that resolves `dosToken` to the actual secret is `WorkerContext.resolveConfigSecrets()`. It's called in [`ScannerRunner.run()`](https://github.com/eclipse-apoapsis/ort-server/blob/3ce0109ad0e7654b10859537e6bd81bdc8322fc1/workers/scanner/src/main/kotlin/scanner/ScannerRunner.kt#L57) but not in [`EvaluatorRunner.run()`](https://github.com/eclipse-apoapsis/ort-server/blob/9cac3a0777443c16f7569d4368c2588befd02da3/workers/evaluator/src/main/kotlin/evaluator/EvaluatorRunner.kt#L67).

That could explain why a literal `dosToken` is used as the value of the secret - because the real value is not resolved anywhere?

**Comment by Etsija** [comment]
> > the server tries to use a literal key `dosToken` as the value
> 
> I'm very surprised that this is not _always_ the case, also for the scanner. Is there maybe some config transformation or so configured for the scanner, that is not configured for the evaluator?

I don't think so. This is [DOS scanner config code](https://github.com/oss-review-toolkit/ort/blob/main/plugins/scanners/dos/src/main/kotlin/DosScannerConfig.kt), and for the DOS PCP, [the config class is inlined](https://github.com/oss-review-toolkit/ort/blob/3f8f078fb0231cd106acf175b042cd44116a3b34/plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt#L48-L57) to the same file as the implementation.

We have been using the same configuration structure as given in the description of this issue for both plugins for a long time now, with no problems.

**Comment by mnonnenmacher** [comment]
I will prepare a fix.

**Comment by Etsija** [comment]
> I will prepare a fix.

Thanks! This is our (almost) last hurdle in integrating our solution into ORT server, so let's hope the fix isn't too complicated.

**Comment by Etsija** [comment]
Thanks @mnonnenmacher nice work fixing this. We have successfully integrated both our scanner and package config provider into ORT server now.
