### ISSUE TITLE
Support the notifier job configuration

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#618]
Add support for the notifier job configuration to the form to create a new ORT run. Also show the notifier job configuration in the run details.

**Comment by Etsija** [comment]
Can I ask you about the `username` and `password` fields of Notifier configuration: are they really not secrets?
```
    "notifier": {
      "notifierRules": "reporter.notifications.kts",
      "resolutionsFile": "resolutions.yml",
      "mail": {
        "recipientAddresses": [
          "mail@example.com",
          "info@example.com"
        ],
        "mailServerConfiguration": {
          "hostName": "smtp.example.com",
          "port": 587,
          "username": "user",
          "password": "password",
          "useSsl": true,
          "fromAddress": "no-reply@example.com"
        }
      },
      "jira": {
        "jiraRestClientConfiguration": {
          "serverUrl": "https://jira.example.com",
          "username": "user",
          "password": "password"
        }
      }
    },
```

**Comment by Etsija** [comment]
ORT run creation form is already over 1000 lines long, so we're probably going to do some refactoring to it before adding new configurations.

**Comment by mnonnenmacher** [comment]
> Can I ask you about the `username` and `password` fields of Notifier configuration: are they really not secrets; so they are exposed in the UI?

Good point, they are treated as secrets, so the values are paths to secrets in the secret storage.

**Comment by Etsija** [comment]
> > Can I ask you about the `username` and `password` fields of Notifier configuration: are they really not secrets; so they are exposed in the UI?
> 
> Good point, they are treated as secrets, so the values are paths to secrets in the secret storage.

Thanks, so it's safe for us to expose them in the form as ordinary text inputs.
