### ISSUE TITLE
Redirect to detail pages instead of list after creating new entities in the UI

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#628]
Creation of a new organization should redirect to that organization's detail page at `/organizations/$orgId`, not the organization list at `/organizations`. Same applies for products, rand repos.

**Comment by Etsija** [comment]
Can you explain why?

**Comment by sschuberth** [comment]
I guess because the assumption is that, from a workflow perspective, it's likely that after creating an organization, you'd want to create products and repos as well, and thus being already on the right screen for that is convenient.

**Comment by mmurto** [comment]
IME it's usually expected behaviour when creating new entities in software, and the most likely path for the user is probably that they want to do something with the entity after they've created one.

**Comment by Etsija** [comment]
What about create-run?
