### ISSUE TITLE
Clicking on a (finished) job status circle should take me to that job's results

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#643]
For example clicking on the analyzer job circle at

![image](https://github.com/eclipse-apoapsis/ort-server/assets/349154/c4c560c6-c5d0-4ae4-bb7c-1963b975e6e9)

should take me straight to

![image](https://github.com/eclipse-apoapsis/ort-server/assets/349154/b32cab27-6b5d-4454-af05-2c99adefa65f)

**Comment by Etsija** [comment]
Note to myself: this could probably be used.
https://tanstack.com/router/latest/docs/framework/react/guide/navigation#hash-links

**Comment by Etsija** [comment]
Implemented with #917.
