### ISSUE TITLE
Show the creation time in the ORT runs table

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#656]
Currently, the ORT runs table only shows the date when a run was created. Also show the time, because the date alone is not sufficient information when many runs were started on the same day.

![image](https://github.com/eclipse-apoapsis/ort-server/assets/2741977/a3b0308a-e167-4d38-91b6-f8e6f5ee932b)

**Comment by sschuberth** [comment]
Somewhat related, after reading though [this](https://momentjs.com/docs/#/-project-status/recommendations/) I wonder whether we should stop using `new Date()` and rather use a library that could also be used to replace our own `calculateDuration()`, which I'd like to show days as well. @mmurto any opinion?

**Comment by mmurto** [comment]
I think we're relatively safe with the native `Date` as all timestamps come from the database and I'd assume they're well and consistently formatted. I've used [date-fns](https://date-fns.org/) for more advanced stuff, it's good.

Where did you run to showing days? Isn't it currently used for run durations, I'd like to believe they're more in the minutes and hours range. :D

**Comment by sschuberth** [comment]
> Where did you run to showing days?

Check global run ID 6 in our instance 😉
