### ISSUE TITLE
Set up `.github/CODEOWNERS`

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#74]
We should have code ownership to auto-assign reviewers, esp. once #57 is merged and we'll have frontend / backend code.

**Comment by sschuberth** [comment]
Actually, I just saw that the file is already there, but probably contains wrong groups, and does not seem to be used to auto-assign reviewers to PRs.

**Comment by mnonnenmacher** [comment]
I have made an update to the CODEOWNERS, I will check if we can create visible teams for frontend or backend developers once any frontend developers have become project committers.

**Comment by mnonnenmacher** [comment]
@sschuberth Regarding the auto assignment of codeowners as PR reviewers, do you suggest to enable the "Require review from Code Owners" option in the branch protection rule or how else would that work?

**Comment by sschuberth** [comment]
> do you suggest to enable the "Require review from Code Owners" option

IIUC that's not necessary, a `CODEOWNERS` file should [be used also without that option](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-forks) as soon as it's there. At least that's how it work in ORT core, where we also do not have "Require review from Code Owners" enabled, but do get auto-assigned reviewers.

**Comment by sschuberth** [comment]
Auto-assigning reviewers works now, so let's close this and maintain code ownership going forward.
