### ISSUE TITLE
Improve linking to a run's details view

### ISSUE THREAD

**Issue by hanna-modica** [eclipse-apoapsis/ort-server#783]
I would like to enter the details view of a run, no matter where in the overview I click on it (except for the rerun button). Currently, I have to click on the tiny number, which is not very intuitive. 

See screenshot:

![image](https://github.com/user-attachments/assets/ea37f28e-72bf-4868-aac2-e03781964edb)

**Comment by sschuberth** [comment]
> I would like to enter the details view of a run, no matter where in the overview I click on it (except for the rerun button).

That request conflicts a bit with https://github.com/eclipse-apoapsis/ort-server/issues/643, and I'd argue that the full row being clickable is not intuitive either / an unusual UX.

> Currently, I have to click on the tiny number, which is not very intuitive.

Do you really mean "not intuitive" (e.g. you'd expect that clicking the number does something else), nor do you mean that it's hard to click the tiny number? If the latter, would it help to make the number a button as well, similar to `Rerun`?

**Comment by hanna-modica** [comment]
Hi @sschuberth,

>  I'd argue that the full row being clickable is not intuitive either / an unusual UX.

I do think, that it is intuitive in order to drill down, you click the whole item. I noticed in a few meetings with screen share that people struggled a bit (including me) to find the next-level information

> Do you really mean "not intuitive" (e.g. you'd expect that clicking the number does something else), nor do you mean that it's hard to click the tiny number? If the latter, would it help to make the number a button as well, similar to Rerun?

No, I do not expect the number to do something else, I rather find it unintuitive, that this is the only place to drill down. However, I see, that there could be reasons to not have all columns lead to the run information directly, so making the number large, would already help. But I would think, also clicking on e.g. finished/failed should lead me to the run information. So any row, that does not need to lead somewhere else (like the #643 you mentioned), I would prefer to drill down to the run information.

However, I do not hold the holy grail and are open to debate.

**Comment by sschuberth** [comment]
@mmurto, any UX remarks here from your side? Maybe indeed buttons would be good enough if "artificially enlarged" by adding an "ID" prefix to each number?

**Comment by mnonnenmacher** [comment]
I don't think it's unusual to make the whole line or at least most of the line clickable. Compare, for example, with GItHub's notification table:

![image](https://github.com/user-attachments/assets/cbf462af-be92-415e-9e80-1a168d2e0743)

Here the whole area that contains the title is clickable and links to the notification details, but some parts like the checkbox on the left or the profile pictures on the right link to other places.

**Comment by mmurto** [comment]
> @mmurto, any UX remarks here from your side? Maybe indeed buttons would be good enough if "artificially enlarged" by adding an "ID" prefix to each number?

I do agree that the numbers are quite small for primary action. Some apps (like Linear for example) do use the pattern that clicking on anywhere on the row opens the items, unless the user clicks on a part that should do something else, so it's not unheard of, and that way it wouldn't conflict with #643.

GitHub on the other hand (for issues as an example) uses the name of the entity as the link and other parts do nothing. We could combine the ID and date for a longer element to use as a link, but I'm not sure if that looks very good.

A third option would be adding a "Run details ->" button, which would be easy to click and very specific, but take up space. Or the IDs could be make larger, maybe by just wrapping it in a button component to give it borders and maybe an icon. I feel just adding "ID" or "Run" or something makes it look odd, but haven't tried it.

Maybe it would make sense to try the first option, so whole row is link except buttons that should do something else, and keep the number looking like a link to give a hint that it can be expanded. I find it a little strange, but of the solutions above, I think it's the best.

**Comment by sschuberth** [comment]
> Here the whole area that contains the title is clickable

Ok. In other words it's just a single cell of the row that's clickable :wink:

**Comment by sschuberth** [comment]
I just realized that the "Action*s*" column has a plural name, whereas we currently only have the single "Rerun" action. So how about adding a "View" or "Details" button before "Rerun", also with an icon, in addition to linking the number from the first column?

**Comment by sschuberth** [comment]
@Etsija I saw too late that you've assigned this to yourself. Did you start already? I also now have something in https://github.com/eclipse-apoapsis/ort-server/compare/view-run-details.
