### ISSUE TITLE
Publish (some of) the project's JARs to Maven Central

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#803]
There are some parts of the ORT server which would make sense to be available as JAR artifacts. One example is the [config-worker](https://github.com/eclipse-apoapsis/ort-server/tree/main/workers/config) project that contains the [ValidationScriptTemplate](https://github.com/eclipse-apoapsis/ort-server/blob/main/workers/config/src/main/kotlin/ValidationScriptTemplate.kt). In order to set up IntelliJ IDEA / Fleet to allow for auto-completion of such scripts, currently a [dummy project](https://github.com/oss-review-toolkit/ort-config/commit/d6d110ede23932aa53eff47d55cc8b7db2a4b649) needs to be set up that depends on the artifact that contains the script template.

**Comment by mnonnenmacher** [comment]
I have requested the creation of an OSSRH account:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5066

**Comment by mnonnenmacher** [comment]
Published artifacts of the release candidates can be found here:
https://central.sonatype.com/search?q=org.eclipse.apoapsis.ortserver
