### ISSUE TITLE
Get user roles from userinfo endpoint instead of ID token

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#814]
Currently, the UI gets the user roles from the ID token returned by Keycloak on authentication. When a user has many roles this can be problematic, because the ID token is passed as an URL parameter to the redirect URI, and the maximum URL length could be exceeded.

To avoid this issue, use the [OIDC userinfo endpoint](https://connect2id.com/products/server/docs/api/userinfo) to get the roles for the authenticated user.

**Comment by Etsija** [comment]
@lamppu has taken this to herself.
