### ISSUE TITLE
Improve editing of hierarchy element names / descriptions

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#831]
Currently the edit button, e.g. for products, is displayed next the name although it actually also refers to the description, and clicking it opens a new view.

This could probably be simplified by making the name and description inline editable, similar to like the [Linear](https://linear.app/) issue tracker does it in several places, like issue titles. However, Linear does not currently seem to offer a way to discard changes when inline editing. I propose to simply allow pressing `Esc` for that, or maybe display some dynamic "Cancel" button while editing.

**Comment by Etsija** [comment]
As with #1706 we now have implemented separate Settings pages for organizations, products and repositories, with edit functionality as well as the GitHub-style Danger Zones for deletion, which resolves #529, I would suggest this issue to be closed as obsolete/not needed anymore.
