### ISSUE TITLE
Adding repositories should preselect the detected VCS type

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#832]
We should use ORT's `VersionControlSystem.forUrl()` to automatically determine the correct VCS type to avoid the user having to select it manually. It should still be possible to override the auto-detected type though, just in case. This probably requires a dedicated API endpoint for the frontend to use unless we want to duplicate some of ORT's logic in frontend code directly, like made only the static URL parsing (ORT also does dynamic probing as a fallback).

**Comment by mmurto** [comment]
A simple thing we could do in the meantime is to set Git as the default, as I'd guess most repos are Git so it would be effectively the same for the majority of users.

**Comment by sschuberth** [comment]
We should probably also probe the default remote branch name as well.

**Comment by sschuberth** [comment]
> We should probably also probe the default remote branch name as well.

Given that the VCS type depends on the URL and is entered when creating a repository entry, but the revision is entered for each run, detecting the default remote branch name is actually a quite different issue.

Also, for now the change to [make Git the default VCS type](https://github.com/eclipse-apoapsis/ort-server/pull/892) turns out to be good enough in all cases I came across so far, so I'm just closing this.
