### ISSUE TITLE
The run overview page should show the ongoing duration for active runs

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#833]
Currently, the "Duration" column just show the total duration for finished runs. However, it'd also be interesting for how long an active runs has been running until now. Probably that "dynamic" time could displayed in the same column, but somehow visually different than the "static" total runtime once finished.

On a somewhat related note, also the tool tips for the individual "Job Status" circles could, besides the name and status, also display the current / final duration. Of course, data in a tool tip is static, so the time for a running analyzer state would not update while the tool tip it displayed, but once if the tool tip is re-displayed the next time.

**Comment by Etsija** [comment]
@sschuberth how about visually distinguishing the ongoing run duration from a finished run with a little spinning wheel beside the duration? Maybe also some colors could be used there, but the spinning wheel is quite universally regarded as a symbol for an ongoing process which is not yet finished.

**Comment by sschuberth** [comment]
> with a little spinning wheel beside the duration?

I'm not against having such a spinning wheel, but I'd still like to see the ongoing duration / current runtime in numbers as well.

**Comment by Etsija** [comment]
Sry if I wasn't clear - current runtime for ongoing runs, total time for finished or failed jobs.
