### ISSUE TITLE
Remove the spinner from page index edit fields

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#835]
In the pagination footers, there is little need for having a spinner inside of the page index edit field: If you wanted to just increment the page index, the arrow button could be used instead. So to declutter the UI, simply remove those spinners. This also avoids visual confusion with the sipper-like combox-popup in the "Items per page" field.

**Comment by sschuberth** [comment]
Probably not related, but as part of #783 I realized that sometimes the page index field also seem to take up too much screen space:

![image](https://github.com/user-attachments/assets/d9752159-0490-4571-8b27-82abf5f78ca0)

Maybe that could be addressed along the way?

**Comment by Etsija** [comment]
Note to myself: [here are some tricks](https://stackoverflow.com/questions/71296535/how-to-remove-arrow-on-input-type-number-with-tailwind-css) to remove the up/down buttons from input fields, by specifying an extra class for it.

**Comment by Etsija** [comment]
Closed with PR #864.
