### ISSUE TITLE
Add a link next to the global run ID to download logs for a completed run

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#836]
As a follow-up to https://github.com/eclipse-apoapsis/ort-server/issues/293 and independent of https://github.com/eclipse-apoapsis/ort-server/issues/168 I believe we should already be able to get logs via the `https://ort-api.scw.doubleopen.io/api/v1/runs/${runId}/logs` endpoint. This functionality should be made available via the UI, e.g. on the run details page in the `Global run ID` row, like

Global run ID | 155 ([download log](https://ort-api.scw.doubleopen.io/api/v1/runs/${runId}/logs))

**Comment by Etsija** [comment]
Can be closed now, with #862?

**Comment by sschuberth** [comment]
Let's use the opportunity and leave this open to make a fine refinements:
- Only logs of stages that were actually enabled for the run should be requested. So if e.g. the advisor stage was disabled, no advisor logs should be requested. Otherwise we end up with dummy 0-byte files in the archive, see 
![image](https://github.com/user-attachments/assets/f30d4d12-4350-4df9-a93f-8dde32cc734c)
- The downloaded file should have a unique name and not always be named `log.zip`, to ease handling of multiple log archives. I propose to add include the global run ID, like `logs-global-run-NNN.zip`.
- My original idea as mentioned above was to add the download button "in the `Global run ID` row" in order to not waste vertical screen space. But I guess we can leave it in the new row now until we have decided where stage-specific logs would be shown.

**Comment by sschuberth** [comment]
> The downloaded file should have a unique name

See https://github.com/eclipse-apoapsis/ort-server/pull/865.

**Comment by sschuberth** [comment]
> Only logs of stages that were actually enabled for the run should be requested.

See https://github.com/eclipse-apoapsis/ort-server/pull/869.

**Comment by sschuberth** [comment]
> * My original idea as mentioned above was to add the download button "in the `Global run ID` row"

IMO we can now make good use of the fact that the download button is on its own row by adding some radio buttons / a combo box that allows to choose the log level once #869 is merged.

**Comment by Etsija** [comment]
See #871. I believe all the tunings for this issue are now done.

**Comment by sschuberth** [comment]
> I believe all the tunings for this issue are now done.

Once every PR is actually merged, yes.
