### ISSUE TITLE
Create an admin view for all currently active runs in a server instance

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#837]
As an admin for a whole instance, I'd like to quickly get an overview over the runs that are currently active in any organization on that instance. It's basically a runs overview page that is not limited to a single repository.

Similarly, probably such overview pages would also be useful on product and organization levels, for admins for those levels respectively.

The main use-case is not to estimate the load on the server, but to get an overview when multiple runs triggered in different organization / products are finished.

**Comment by sschuberth** [comment]
As a note, such overview pages should probably be filterable by the user who triggered the run.

**Comment by sschuberth** [comment]
> Do you think it would be more beneficial to just see the active runs

Originally I was just thinking about active runs, but now that you suggest it, I guess being able to globally filter all runs also could be nice, e.g. to identify jobs that took exceptionally long across all orgs.

In any case, I believe only showing active runs would be a good default filter.

What do @mmurto and @mnonnenmacher think?

**Comment by mnonnenmacher** [comment]
I think the endpoint was already implemented so that you can filter by statuts, so I would definitely also support that in the UI. Regarding the default filter I have no strong opinion, but a tendency towards setting none, otherwise the view would often be empty for not so active instances.

**Comment by mmurto** [comment]
I feel no default filter makes sense, I think it gives a better overview at a glance on what has happened as well as the currently running jobs.

**Comment by sschuberth** [comment]
> but a tendency towards setting none, otherwise the view would often be empty for not so active instances.

I don't think that having an empty view in such cases would be a problem, but I also have no strong opinion here, just a personal preference for my use-case to watch active runs / server load.

**Comment by mnonnenmacher** [comment]
> my use-case to watch active runs / server load.

For that a Grafana board works better, like:
![image](https://github.com/user-attachments/assets/71f442fa-fec1-4049-a6a4-105ec4363d23)

**Comment by sschuberth** [comment]
This was done in https://github.com/eclipse-apoapsis/ort-server/pull/1238.
