### ISSUE TITLE
Docker Compose environment broken after PR #855?

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#859]
After PR #855 from yesterday, I cannot access any services anymore, so the environment seems to be broken. `docker container ls` gives me "unhealthy" from 

```
64b9eb93d41a   ghcr.io/eclipse-apoapsis/ort-server-ui:main                 "/entrypoint.sh"         4 minutes ago   Up 2 minutes (unhealthy)   80/tcp, 0.0.0.0:8082->8080/tcp, :::8082->8080/tcp
```

Has the process of starting the DC env. changed since yesterday? I'm always doing `docker compose pull && docker compose up -d`.

To conclude, none of these services connect:
![Capture](https://github.com/user-attachments/assets/ee3b1bce-9348-4a05-a600-4227f338ccfb)

**Comment by Etsija** [comment]
I have these env. variables set up in my `.env.local`:
```
VITE_API_URL=http://localhost:8080
VITE_AUTHORITY=http://localhost:8081/realms/master
VITE_UI_URL=http://localhost:5173/
VITE_CLIENT_ID=ort-server-ui-dev
VITE_RUN_POLL_INTERVAL=5000
```

**Comment by Etsija** [comment]
This seems to have been one of those "restart your PC" type of problems.

**Comment by sschuberth** [comment]
@Etsija, please remember to close these kind of issues as "can't repro" from the drop down.
