### ISSUE TITLE
Pressing the `Enter` key does not work to submit a rename

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#918]
When renaming e.g. an organization, the renaming works then clicking `Submit` with the mouse, but it does not work when pressing the `Enter` key after editing the name. I.e. it seems the `Enter` key is not bound to the `Submit` action, but to the `Cancel` action.

**Comment by mmurto** [comment]
Should work by adding `type="button"` to the cancel button.

**Comment by Etsija** [comment]
> Should work by adding `type="button"` to the cancel button.

It doesn't, though, now pressing enter just performs the cancel function.

**Comment by Etsija** [comment]
The problem might be that we have both Cancel and Submit buttons in the form. If I remove the Cancel button, enter submits as requested. Do we actually need the Cancel button in edit forms, as there are no such in add forms?

**Comment by Etsija** [comment]
If we can agree on how to fix this, I can do it, and meanwhile, add the `autoFocus` to the first fields of edit forms while I'm at it.

**Comment by sschuberth** [comment]
I don't think we should remove the cancel button just because we don't know how to get the button focus right. Cancelling by navigating away via the breadcrumb is not a good UX, IMO.

> Should work by adding `type="button"` to the cancel button.

I was surprise by this, as I would have expected this needs to go to the submit button, to make it the default button.

But anyway, I believe it makes sense to list the more likely default action first, and first means to the left for us, so I'd simply swap the order of the buttons.
