### ISSUE TITLE
Change the way the "Download <LEVEL> log archive" button works

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#920]
After having used it a bit, I believe we should change the way the button works: Instead of starting the download immediately when choosing another level from the drop-down, choosing another level should change the title of the main button and require another click to perform the actual download.

This would be in-line with how e.g. GitHub's "Update branch" button works:

![image](https://github.com/user-attachments/assets/b573cbc8-7421-4d0d-abb0-99adc575d1ee)

After clicking on "Update with rebase", the main button changes to

![image](https://github.com/user-attachments/assets/30146c1a-0e3e-463d-9b91-573943798624)

and requires another click to perform the actual update.

**Comment by Etsija** [comment]
This was the way it was initially, but I changed it due to review comments. Will change it back.

**Comment by mnonnenmacher** [comment]
We have so much free space on that page, why not make separate buttons for each log level? Then you need only one instead of three clicks.

**Comment by sschuberth** [comment]
> Then you need only one instead of three clicks.

Why three? I believe it's at most two: 1) Select level, 2) download. Anyway, we're still experimenting with UX and the UI in general, and we're unsure how much more information will get shown on that page, or whether the button will be moved elsewhere.

**Comment by mnonnenmacher** [comment]
> Why three?

1. Open dropdown
2. Select level
3. Download
