### ISSUE TITLE
Improve presentation of labels and parameters

### ISSUE THREAD

**Issue by mnonnenmacher** [eclipse-apoapsis/ort-server#937]
With the new run UI labels and parameters are shown in a string which provides bad overview if many are used:
![parameters](https://github.com/user-attachments/assets/a7ab43e8-f83a-4ea8-bd52-fe5d7d60b0a1)

It would be better to show one entry per line.

**Comment by Etsija** [comment]
Thanks for a nice use case; we've not had experience yet of using so many labels and parameters.  I'll assign this to myself.

**Comment by Etsija** [comment]
@mnonnenmacher it would help me a lot, if you could provide me a "typical" set of labels and parameters you use - excluding all confidentials, of course. Any textual format would be fine; key-value pairs would work best.

**Comment by mnonnenmacher** [comment]
I'll just put it here:

Labels:

applicationCategory = some category
transport.kubernetes.javaVersion = 21-

Parameters:

reports = AsciiDocDisclosureDocument,CtrlXAutomation,CycloneDX,EvaluatedModel,HtmlDisclosureDocument,OrtResult,PdfDisclosureDocument,SpdxDocument,StaticHTML,Vulnerabilities,WebApp,FossID
javaVersion = 21
fossIdServer = servername
skipExcluded = true
fossIdProjectName = PROJECT_NAME
useClearlyDefined = true
applicationCategory = CATEGORY_NAME
fossIdUseDeltaScans = true
fossIdWaitForResult = true
businessUnitTemplate = template-name
fossIdDeltaScanLimit = 15
fossIdKeepFailedScans = false
createSourceCodeBundle = false
sourceCodeBundlePackageTypes = PACKAGE
fossIdFetchSnippetMatchedLines = false
fossIdDetectCopyrightStatements = false
fossIdDetectLicenseDeclarations = false

**Comment by Etsija** [comment]
Could look nicer I think, what do you say?

![Capture](https://github.com/user-attachments/assets/33a2b446-5c53-4fb8-ba8c-5fdb7f50478c)

**Comment by Etsija** [comment]
...or this? Throwing out some ideas to you 😄 It's pretty tricky to do aligning without a table, which I think is a bit of an overkill here, making that as compact as this will be tricky as well.

![Capture](https://github.com/user-attachments/assets/ceb408a9-cc8e-4133-a88d-3e7403e1fa71)

**Comment by mnonnenmacher** [comment]
Maybe a combination of both, align the keys on the left like in the first example but also align the `=` like in the second example?

**Comment by sschuberth** [comment]
So like a 2-column table with invisible borders, basically?

**Comment by Etsija** [comment]
This smells like a Grid layout to me. OK thanks for your feedback, I'll continue with this later.
