### ISSUE TITLE
Publish the Swagger UI (to GitHub pages)

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#94]
It would be convenient to have the Swagger UI available without building the project locally, so auto-publishing the latest Swagger UI e.g. to GitHub pages would be great. Maybe these projects could help:

* https://github.com/peter-evans/swagger-github-pages
* https://github.com/Legion2/swagger-ui-action

**Comment by Etsija** [comment]
I second this, would be helpful to see and inspect the API even without building the project.

**Comment by Etsija** [comment]
Now as our initial Server UI is in the codebase, we would really need this for planning the way forward; access to the API spec via GitHub would be very beneficial, as not everyone in our team wants to always run the local setup just to be able to inspect the API.

**Comment by sschuberth** [comment]
@mnonnenmacher is there a way to prioritize this? This would be really convenient for front-end development still.

**Comment by sschuberth** [comment]
Mostly, yes, but as you know there are still [issues with the Compose setup](https://github.com/eclipse-apoapsis/ort-server/issues/168), and for quickly looking up something it'd be more convenient to have a public reference. But I just realized I could also just use Swagger from our staging deployment.

**Comment by mnonnenmacher** [comment]
I have done some testing with https://github.com/PaloAltoNetworks/docusaurus-openapi-docs and it looks promising:

![grafik](https://github.com/user-attachments/assets/af996756-a56d-46a0-8926-404edb912634)

It currently fails for some endpoints due to invalid specs, but once #946 is merged I will look into adding this.

**Comment by mnonnenmacher** [comment]
The API docs are published at https://eclipse-apoapsis.github.io/ort-server/api/ort-server-api.
