### ISSUE TITLE
Add an endpoint to get the packages for projects

### ISSUE THREAD

**Issue by sschuberth** [eclipse-apoapsis/ort-server#940]
In the front-end, we'd like to show the dependencies immediately after an analyzer run, e.g. as a flat list of de-duplicated packages, either per project, or even across all projects.

The UI could be a table that contains the parent project as a column which can be filtered for. As a quick action, I imagine having an "Export SBOM" button here that would only use the currently visible / filtered packages as the input. This would allow to create SBOMs per project, but also to omit packages with certain filtered properties from the SBOM.

**Comment by mnonnenmacher** [comment]
I would split that into two issues, one for the list and one for the graph, because I think that the graph feature is a lot more difficult to implement.

**Comment by sschuberth** [comment]
Done. I've edited this issue to be for the list, and created https://github.com/eclipse-apoapsis/ort-server/issues/944 for the graph.

**Comment by lamppu** [comment]
@mnonnenmacher would it be ok on your side if I gave this one a try?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher would it be ok on your side if I gave this one a try?

@lamppu Yes, we have currently not planned to start working on it and it should also not be less complicated than the vulnerabilities endpoint.

**Comment by sschuberth** [comment]
> not be less complicated

Hopefully the "not" was wrong here 😆

**Comment by Etsija** [comment]
@sschuberth can this be closed now, as Johanna's PR is merged? Although, for this endpoint to be used as you've described, it also needs the dependency trees of packages, so the two issues, this and #944 are probably coupled.

**Comment by sschuberth** [comment]
Yeah, I agree that I mixed too much of #944 into this. So let's close this as https://github.com/eclipse-apoapsis/ort-server/pull/1072 implemented what I was mainly after.
