### ISSUE TITLE
Add more icons to the UI

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#948]
As [this commit](https://github.com/eclipse-apoapsis/ort-server/commit/ef1ce83f0e9c93f685c8af441cf89d040f9219cf) added an icon props to sidebars, and #939 already revised some of the exemplary icons put there, we could maybe think of providing good describing icons to other sidebars as well:
- use a general Overview icon everywhere - or, a different one for Organizations, Products and Repositories?
- an icon for Secrets
- an icon for Infrastructure Services
- does the "Technical" section of the run details sidebar need icons as well? Logs, Reports, Job configs, Issues?

To me, using carefully selected icons in the UI is not just a matter of "eye candy" - icons often "teach" more visually thinking users in where to find what, and should lead to a better UX. The Issues and Pull requests icons in GitHub are some good examples.

**Comment by sschuberth** [comment]
Smells a bit like a design guideline...

**Comment by Etsija** [comment]
Could a secret be represented with a key icon, for example [this](https://lucide.dev/icons/key-square)?

**Comment by sschuberth** [comment]
> Could a secret be represented with a key icon, for example [this](https://lucide.dev/icons/key-square)?

I'd prefer something like https://lucide.dev/icons/book-lock.

**Comment by Etsija** [comment]
Then we would need a good representative icon for infrastructure services, and I could add them (Overview, Serets, Infrastructure services) to the UI sidebar menus. Tried to search for a suitable one but nothing obvious popped up.

**Comment by sschuberth** [comment]
> a good representative icon for infrastructure services

Maybe https://lucide.dev/icons/server-cog?
