### ISSUE TITLE
Deduplicate UI query options

### ISSUE THREAD

**Issue by mmurto** [eclipse-apoapsis/ort-server#976]
Many components specify diplicate query options in the component and in the loader, like:

https://github.com/eclipse-apoapsis/ort-server/blob/be0c8973d76871f0f90c0d4ed9ec02b005948a87/ui/src/routes/_layout/organizations/%24orgId/products/%24productId/repositories/%24repoId/_layout/runs/%24runIndex/index.tsx#L47-L66

https://github.com/eclipse-apoapsis/ort-server/blob/be0c8973d76871f0f90c0d4ed9ec02b005948a87/ui/src/routes/_layout/organizations/%24orgId/products/%24productId/repositories/%24repoId/_layout/runs/%24runIndex/index.tsx#L220-L231

To reduce repetition and possibility for errors, these should be replaced with TanStack Query's `queryOptions()` like [this](https://tanstack.com/router/latest/docs/framework/react/guide/external-data-loading#a-more-realistic-example-using-tanstack-query).

**Comment by Etsija** [comment]
This has been nagging me for a while now, so I could take it under work.
