### ISSUE TITLE
UI: Re-running an ORT run discards `repositoryConfigPath`

### ISSUE THREAD

**Issue by nnobelis** [eclipse-apoapsis/ort-server#985]
I have a run with `repositoryConfigPath` set in the Analyzer job:

```
  "allowDynamicVersions": false,
  "repositoryConfigPath": "applications/abc/.ort.yml",
  "packageManagerOptions": {
    "NPM": {
      "options": {
        "legacyPeerDeps": "true"
      }
    },
    "Yarn2": {
      "options": {
        "corepackOverride": "true"
      }
    }
  },
  "enabledPackageManagers": [
    "BAZEL",
    "BOWER",
    "BUNDLER",
    "CARGO",
```

**Problem 1**  `repositoryConfigPath` is not visible in the UI:

![image](https://github.com/user-attachments/assets/53be62e1-6e8d-4e1f-9df8-65d9a71efc0f)

**Problem 2** If I choose re-run in the UI, the new run does not have a `repositoryConfigPath` anymore.

**Comment by Etsija** [comment]
This is because we've taken an opinionated priorisation to adding new job configuration parameters to the UI, and `repositoryConfigPath` handling is missing totally from the UI.

**Comment by Etsija** [comment]
@nnobelis see whether #1069 resolves your issue. I tested it with the default path `.ort.yml` given to the run explicitly. Now the `repositoryConfigPath` is supported in the UI (create run, Rerun functionality, and results/job configurations/Analyzer).

**Comment by nnobelis** [comment]
@Etsija Thanks a lot for the PR. I will test it as soon we can put it n production.

**Comment by Etsija** [comment]
Apparently #1069 didn't close this automatically.
